### ISSUE TITLE
Localhost error

### ISSUE THREAD

**Issue by H3R0BRINE** [altogic/altogic#11]
Hi there,
When I created my own custom website on verification of the link the link is towards localhost:3000

**Comment by H3R0BRINE** [comment]
My girl repo : https://GitHub.com/BLI-P/IRONHIDE.git

**Comment by zinedkaloc** [comment]
Hey, sorry for late answering :  You can update it from the **Settings → Authentication → Redirect URL** view of Altogic Designer.

![CleanShot 2023-01-12 at 13 16 49@2x](https://user-images.githubusercontent.com/104208669/212040528-cb8e53d2-f6ae-4846-bc4c-35d33e579a7c.png)

For more information please visit : https://www.altogic.com/client/guides/authentication/sign-in
