### ISSUE TITLE
Altogic

### ISSUE THREAD

**Issue by UTKUC3NGIZ** [altogic/altogic#9]
A

**Comment by zinedkaloc** [comment]
Hey @UTKUC3NGIZ ? What is your issue?

**Comment by UTKUC3NGIZ** [comment]
hi, I'm sorry it was accidental.

Deniz ***@***.***>, 14 Ara 2022 Çar, 14:43 tarihinde şunu
yazdı:

**Comment by zinedkaloc** [comment]
No worries 🙏 just closing this issue 👋🏼

**Comment by UTKUC3NGIZ** [comment]
Thank you😇

Deniz ***@***.***>, 16 Ara 2022 Cum, 08:57 tarihinde şunu
yazdı:
